version: "3.4"

services:
  c-dev:
    image: "riscv:1.3"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/jia/work
    user: "jia"
    working_dir: /home/jia/work
    command:
      bash -c "sudo service ssh restart && tail -f /dev/null"
    ports:
      - "127.0.0.1:2222:22"
